# This file is relaated to the lessons "Step 2 - Configure new Reusable Workflow"

name: Deployment in k8s Reusable WF_2

on:
  workflow_dispatch:
  push:
     branches:
       - main
       - feature/**
 
env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
  unit-testing:
    name: Unit Testing
    strategy:
      matrix:
        nodejs_version: [20] #[19, 20]
        operating_system: [ubuntu-latest] #, macos-latest]
        # exclude:
        #   - nodejs_version: 18
        #     operating_system: macos-latest
    runs-on: ${{ matrix.operating_system }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v5

    - name: Setup NodeJS Version ${{ matrix.nodejs_version }} on ${{ matrix.operating_system }}
      uses: actions/setup-node@v5   
      with:                         
        node-version: ${{ matrix.nodejs_version }}
        
    - name: Install Dependencies
      run: |
        npm install
        
    - name: Unit Testing
      id: nodejs-unit-testing
      run: |
        npm test

  code-coverage:
    name: Code Coverage
    continue-on-error: true
    strategy:
      matrix:
        nodejs_version: [20] #[19, 20] #[18, 19, 20]
        operating_system: [ubuntu-latest] #, macos-latest]
        # exclude:
        #   - nodejs_version: 18
        #     operating_system: macos-latest
    runs-on: ${{ matrix.operating_system }}      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Setup NodeJS Version ${{ matrix.nodejs_version }} on ${{ matrix.operating_system }}
      uses: actions/setup-node@v5
      with:
        node-version: ${{ matrix.nodejs_version }}

    - name: Install dependencies
      run: npm install

    - name: Run coverage
      id: run_coverage
      continue-on-error: true
      run: |
        npm test

  containerization:
    name: Containerization
    needs: [unit-testing, code-coverage]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v5

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    # Prepare QEMU for multi-arch builds
    - name: Set up QEMU emulator
      uses: docker/setup-qemu-action@v3

    # Enable Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image for Testing
      uses: docker/build-push-action@v5
      with:
        context: .
        load: true
        push: false   ### false because we want to test the image before to push it!
        tags: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}   

    # sometimes is useful in a pipeline test the docker image!
    - name: Docker Image Test
      run: |
        docker images
        docker run --name solar-system-app -d \
            -p 3000:3000 \
            -e MONGO_URI=$MONGO_URI \
            -e MONGO_USERNAME=$MONGO_USERNAME \
            -e MONGO_PASSWORD=$MONGO_PASSWORD \
            ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
        
        export IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' solar-system-app)
        echo $IP

        echo "docker ps -a"
        docker ps -a

        # see in the app.js the endpoint "/live" it returns {"status": "live"}
        echo 'Testing Image URL using wget (localhost)'
        wget -q -O - 127.0.0.1:3000/live | grep live
        echo 'Testing Image URL using wget ($IP)'
        wget -q -O - $IP:3000/live | grep live

    - name: Push Docker Image
      uses: docker/build-push-action@v4
      with:
        # in my opinion is not a good idea rebuild the image
        # if we passed the previoust test we've to push the same image we tested!!!
        context: .
        push: true
        tags: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}

  dev-deploy:
    needs: containerization
    if: contains(github.ref, 'feature/')
    uses: ./.github/workflows/solar-system-k8s-reuse-deploy-wf_2.yaml
    secrets: # I don't use inherit here!
      k8s-config: ${{ secrets.KUBECONFIG }}
      mongo-db-pwd: ${{ secrets.MONGO_PASSWORD }}
    
  # we change the name compared the "solar-system-k8s-deployment-dev.yaml" file
  dev-integration-testing:
      name: Dev Integration Testing
      needs: dev-deploy
      # if: contains(github.ref, 'feature/')   ### In my opinion it doesn’t make sense because this step needs on dev-deploy where we have the same condition
      runs-on: ubuntu-latest
      steps:
        - name: Test '/live' Endpoint
          env:
            URL: ${{ needs.dev-deploy.outputs.APP_INGRESS_URL }}
          run: |
            echo $URL

  ### new code for production env
  prod-deploy:
    needs: containerization   ### this steps depends on containerization
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/solar-system-k8s-reuse-deploy-wf_2.yaml
      k8s-config: ${{ secrets.KUBECONFIG }}
      mongo-db-pwd: ${{ secrets.MONGO_PASSWORD }}

  # we change the name compared the "solar-system-k8s-deployment-dev.yaml" file
  prod-integration-testing:
    name: Prod Integration Testing   ### edited for production
    needs: prod-deploy   ### edited for production
    runs-on: ubuntu-latest
    steps:
      - name: Test '/live' Endpoint
        env:
          URL: ${{ needs.prod-deploy.outputs.APP_INGRESS_URL }}   ### edited for production
        run: |
          echo $URL