name: Deployment - Reusable WF_3

on:
  workflow_call:
    secrets:
      k8s-config:
        required: true
      mongo-db-pwd:
        required: true
    inputs:
      mongo-uri: 
        required: true
        type: string
      mongo-username:
        required: true
        type: string
      kubectl-version:
        description: kubectl CLI version
        required: false
        default: v1.32.0
        type: string
      k8s-manifest-dir:
        description: Path to Kubernetes manifests
        required: true
        default: kubernetes/
        type: string
      environment:
        description: Deployment environment name
        required: true
        default: dev
        type: string             
    
jobs:
  reuse-deploy:
    ### down below the code I've copied/pasted!!! (*a*)/(*b*)
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.environment }}
      # if the job deploy somethin the URL is the endpoint of the application
      url: https://${{ steps.set-ingress-host-address.outputs.APP_INGRESS_URL }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install kubectl CLI
        uses: azure/setup-kubectl@v3
        with:
          # version: 'v1.32.0'
          version: ${{ inputs.kubectl-version }}

      - name: Print kubeconfig secret
        run: |
          echo "Print kubeconfig secret --->${{ secrets.k8s-config }}<--- "

      - name: Save Nginx Ingress IP
        id: ingress
        run: |
          echo "INGRESS_IP=ingres.url" >> $GITHUB_ENV

      - name: Replace tokens in manifests
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '_{_'
          tokenSuffix: '_}_'
          files: ${{ inputs.k8s-manifest-dir}}/*.yaml   ### apply in all yaml files!
        env:
          NAMESPACE: ${{ vars.NAMESPACE }}   ### define the proper vars!
          REPLICAS: ${{ vars.REPLICAS }}
          IMAGE: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
          INGRESS_IP: ${{ env.INGRESS_IP }}   ### look at how we define this var above!

      - name: Verify replaced manifests
        run: cat ${{ inputs.k8s-manifest-dir}}/*.yaml

      - name: Create MongoDB Secret
        run: |
          echo "-namespace: ${{ vars.NAMESPACE }}\n-mongo uri: ${{ inputs.mongo-uri }}\n-mongo username: ${{ inputs.mongo-username }}\n-mongo pwd: ${{ secrets.mongo-db-pwd }}\n"
      
      - name: Set App Ingress Host URL
        id: set-ingress-host-address
        run: |
          echo "APP_INGRESS_URL=var_for_host_${{ vars.NAMESPACE }}" >> "$GITHUB_OUTPUT"

    outputs:
      APP_INGRESS_URL: ${{ steps.set-ingress-host-address.outputs.APP_INGRESS_URL }}